Update GoogleTests.java
kristina71/qa-guru-pr1 pull request #1
Opened 2020-08-18 16:13 UTC by AleksandrZhuravel

1. Selectors "q" and "html" replaced by class selectors.

2020-08-18 16:13 UTC, AleksandrZhuravel commented
1. Selectors "q" and "html" replaced by class selectors.

2020-08-18 19:21 UTC, kristina71 requested changes
And also I don't see the Yandex test. You need to create one more test (https://qa.guru/pl/teach/control/lesson/view?id=161420799&editMode=0 - step 3)

2020-08-18 19:21 UTC, kristina71 commented on src/test/java/tests/GoogleTests.java
> +        $(".gLFyf").setValue("Selenide").pressEnter();
`$(".gLFyf")` Perhaps, This is a dynamic class that can be generated when rendering a page. Also, this locator is intuitively incomprehensible when reading code. It is better not to get attached to it.

2020-08-18 19:21 UTC, kristina71 commented on src/test/java/tests/GoogleTests.java
> +        $(".iUh30").shouldHave(text("ru.selenide.org"));
the same problem

2020-08-19 10:49 UTC, kristina71 requested changes

2020-08-19 10:49 UTC, kristina71 commented on src/test/java/tests/GoogleTests.java
> +        open("https://google.com");
Why do you open google.com? You should open yandex.ru and create any test

For example:
`@Test
    void emptySearch(){
        open("https://yandex.ru");
        $(".input__control").setValue("").pressEnter();
        $(".misspell__message").shouldHave(text("Задан пустой поисковый запрос"));
    }`

2020-08-19 10:49 UTC, kristina71 commented on src/test/java/tests/GoogleTests.java
> +        $("html").shouldHave(text("ru.selenide.org"));
What is the difference between this test and the previous one?

2020-08-19 11:23 UTC, AleksandrZhuravel commented
You were right about my request. I reversed my false changes and added new Yandex-test. 
I also reviewed the code in accordance with the wishes of Stanislav Vasenkov and added the UTF-8 encoding to the file "build.gradle".

2020-08-19 11:41 UTC, kristina71 requested changes

2020-08-19 11:41 UTC, kristina71 commented on src/test/java/tests/GoogleTests.java
> +        $("html").shouldHave(text("ru.selenide.org"));// Проверить, что Selenide появился в результатах поиска
better use specific locator like ".organic__subtitle b"

2020-08-19 12:04 UTC, kristina71 approved these changes

2020-08-19 12:08 UTC, AleksandrZhuravel commented
I changed the locator to a locator by class (different from yours) and renamed Java class. You should rename GoogleTests.java according to the Java class name.

2020-08-20 10:41 UTC, merged